version : '3.9'
services :
  app1 :
    image : santoanandj/guvi:v1
    container_name : test1
    ports :
      - 80:80
  app2 :
      image : santoanandj/guvi:v1
      container_name : test2
      ports :
        - 300:80
  app3 :
    image : ubuntu:latest
    container_name : test3
    ports :
      - 85:80

  app4:
    image : nginx:latest
    container_name : test4
    ports :
      - 86:80

